services:
  weatherwise.api:
    container_name: weatherwise-api
    image: ${DOCKER_REGISTRY-}weatherwiseapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      # Adicione sua chave API diretamente aqui para teste
      - OpenWeather__ApiKey=fcd4dc634c8c2e8baea55625d1096881
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - weatherwise-network

networks:
  weatherwise-network:
    name: weatherwise-network
    driver: bridge